backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - file: "index.html"
        label: "Startseite"
        name: "home"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
